Server:
  RunMode: debug
  HttpPort: 9000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  NormalUserDeviceUplimit: 20
  VipUserDeviceUplimit: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
Database:
  DBType: mysql
  Username: root
  Password: admin
  Host: 127.0.0.1:3306
  DBName: iot_service
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
JWT:
  Secret: lee@mplane_8411
  Issuer: MatrixPlan
  Expire: 259200
Email:
  Host: smtp.163.com
  Port: 465
  UserName: XXXX@163.com
  Password: XXXX
  IsSSL: true
  From: XXXX@163.com
  To:
    - XXX@qq.com